<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Mail List Syntax Def (YAML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#list-info</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>list-info</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>title</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>from</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>subject</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>time</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(.{12})(.{39})(.{48})(.{12})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>test</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.mail.list</string>
	<key>uuid</key>
	<string>0df86606-d7a6-4ed7-9a74-8d0c98c793eb</string>
</dict>
</plist>
