<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eml</string>
		<string>email</string>
	</array>
	<key>name</key>
	<string>E-Mail</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#header-field</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>email-addresslist</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^(?i)(From|To|Cc|Bcc)\s*(:)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.email</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.email</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.address.email</string>
			<key>end</key>
			<string>^(?!\s)</string>
		</dict>
		<key>email-attachment</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^\s*([-\*\+])\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.email</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.attachment.email</string>
			<key>end</key>
			<string>$</string>
		</dict>
		<key>email-message</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?i)(\#!re?st)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.email</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.restructuredtext</string>
					<key>end</key>
					<string>(?=^--\s*\n|^\n\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.restructuredtext</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(\#!markdown)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.email</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.restructuredtext</string>
					<key>end</key>
					<string>(?=^--\s*\n|^\n\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>^(--)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.email</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>support.other.signature</string>
					<key>end</key>
					<string>^\n\n</string>
				</dict>
			</array>
		</dict>
		<key>header-field</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?i)(?=From\s*:)</string>
					<key>end</key>
					<string>^(?![\t\x{00000020}])</string>
					<key>name</key>
					<string>meta.address.sender.email</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#email-addresslist</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(?=To\s*:)</string>
					<key>end</key>
					<string>^(?![\t\x{00000020}])</string>
					<key>name</key>
					<string>meta.address.recipient.to.email</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#email-addresslist</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(?=Cc\s*:)</string>
					<key>end</key>
					<string>^(?![\t\x{00000020}])</string>
					<key>name</key>
					<string>meta.address.recipient.cc.email</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#email-addresslist</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(?=Bcc\s*:)</string>
					<key>end</key>
					<string>^(?![\t\x{00000020}])</string>
					<key>name</key>
					<string>meta.address.recipient.bcc.email</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#email-addresslist</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(attach(?:ments?)?)\s*(:)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.email</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.email</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?![\t\x{00000020}])</string>
					<key>name</key>
					<string>meta.attachment.email</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#email-attachment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(subject)\s*(:)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.email</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.email</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?![\t\x{00000020}])</string>
					<key>name</key>
					<string>meta.subject.email</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>applyEndPatternLast</key>
							<integer>1</integer>
							<key>begin</key>
							<string>(?=\S)</string>
							<key>end</key>
							<string>^(?![\t\x{00000020}])</string>
							<key>name</key>
							<string>string.unquoted.subject.email</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>^(Date)\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.email</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.email</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.unquoted.header.email</string>
					<key>end</key>
					<string>^(?![\t\x{00000020}])</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*$</string>
					<key>end</key>
					<string>^\n\n</string>
					<key>name</key>
					<string>meta.message.email</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#email-message</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.email</string>
	<key>uuid</key>
	<string>ecc7917d-555b-4005-a65a-40f92aafe508</string>
</dict>
</plist>
